### ISSUE TITLE
missing file `zero123/stable-diffusion/configs/sd-objaverse-finetune-c_concat-256.yaml` 

### ISSUE THREAD

**Issue by ZENGXH** [cvlab-columbia/zero123#1]
Hi @ruoshiliu, 

Thanks for sharing the code! When I run the 3drec code, it seems the config is missing?

**Comment by ruoshiliu** [comment]
Hi @ZENGXH , sorry about the bug -- it's some directory issues. Just pushed the fix, could you try again?

**Comment by ZENGXH** [comment]
It works now. Thanks!
