### ISSUE TITLE
sd basemodel

### ISSUE THREAD

**Issue by icedCoffe001** [cvlab-columbia/zero123#118]
hello! did you make the zero123 to be a basemodel for stable diffusion and controlnet?
I've seen it on civitai，https://civitai.com/models/231725/stable-zero123.
however，I can't load the model like sd1.5.There is the following error message：
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for ControlLDM: size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
I will be very happy if I get your answer,thanks.

**Comment by icedCoffe001** [comment]
i got it now.

**Comment by immaturehearts** [comment]
How did you fix this, could u help me?

**Comment by icedCoffe001** [comment]
> How did you fix this, could u help me?

see [convert_zero123_to_diffusers.py](https://github.com/huggingface/diffusers/blob/bc691231360a4cbc7d19a58742ebb8ed0f05e027/scripts/convert_zero123_to_diffusers.py)， it may helpful.

**Comment by immaturehearts** [comment]
> > How did you fix this, could u help me?
> 
> see [convert_zero123_to_diffusers.py](https://github.com/huggingface/diffusers/blob/bc691231360a4cbc7d19a58742ebb8ed0f05e027/scripts/convert_zero123_to_diffusers.py)， it may helpful.

Thanks a lot!
