### ISSUE TITLE
Partial Objaverse dataset for demo

### ISSUE THREAD

**Issue by KhanhNgoDuy** [cvlab-columbia/zero123#127]
Can anyone provide a subset (a few GBs) of the rendered images from Objaverse for demo purpose?
1.5TB is too much for me to download.

**Comment by zhaosheng-thu** [comment]
Same questions

**Comment by KhanhNgoDuy** [comment]
@zhaosheng-thu I think for debugging, we can start downloading the file, wait for a few minutes and then interrupt the process. The resulting `tar.gz` file can still be extracted, with only a few images for testing.

**Comment by zhaosheng-thu** [comment]
> @zhaosheng-thu I think for debugging, we can start downloading the file, wait for a few minutes and then interrupt the process. The resulting `tar.gz` file can still be extracted, with only a few images for testing.

Thanks. I find it worked well!
