### ISSUE TITLE
RT matrix from rendering

### ISSUE THREAD

**Issue by dongyh20** [cvlab-columbia/zero123#14]
I'm wondering if the RT matrix is the extrinsic matrix of the camera? And I just want to make sure that in the dataset, this matrix is kept in the transforms.json right? I'm confused because it seems that the RT matrix generated when rendering is different from that of [GET3D](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_shapenet.py), so I want to make sure that I'm doing the right render process and get the extrinsic matrix of the camera.

**Comment by ruoshiliu** [comment]
Hi @dongyh20 , sorry for the delay, the definition of RT matrix can be found here in the rendering script: https://github.com/cvlab-columbia/zero123/blob/865d23e91e9d5d47fdd83273dcfbbabed421b3b9/objaverse-rendering/scripts/blender_script.py#L218
I've updated the rendering command which you can use to render the dataset yourself under [objaverse-rendering](https://github.com/cvlab-columbia/zero123/tree/main/objaverse-rendering):

```
python scripts/distributed.py \
	--num_gpus 8 \
	--workers_per_gpu 2 \
	--input_models_path Objaverse-v1/object-paths.json
```
