### ISSUE TITLE
3D reconstruction with 32GB of GPU RAM

### ISSUE THREAD

**Issue by dheera** [cvlab-columbia/zero123#15]
Hi,
I was wondering what GPU the authors use for `3drec/run_zero123.py`, and if anyone has been successful running it with <=32GB of GPU RAM? The novel view reconstruction works fine but I'm getting a CUDA out of memory error running the 3D reconstruction script. Thanks and great work!

**Comment by jfozard** [comment]
The Pikachu demo works fine for me on a 3090 (Linux)

**Comment by ChrisWu1997** [comment]
It should be able to run under 24GB GPU memory. We have tested it on a ubuntu with 3090.
