### ISSUE TITLE
model for human face

### ISSUE THREAD

**Issue by burning846** [cvlab-columbia/zero123#16]
as you mentioned 'If you are trying out images of humans, especially faces, note that it is unfortunately not the intended use case. We would encourage trying out images of everyday objects instead, or even artworks.' I am wondering whether it's hard to generate 3d model of human faces or the model just still in training and will be released later?

**Comment by ruoshiliu** [comment]
Human faces or human body modeling in general are very exciting future directions. We are currently not training any human models but we will be excited to see follow-up works in this topic.
