### ISSUE TITLE
question about SJC-I

### ISSUE THREAD

**Issue by Tsingularity** [cvlab-columbia/zero123#17]
Hi, thanks for the great work!

I saw in the paper, one baseline called SJC-I was mentioned:"Finally, we adapted SJC [53], a diffusion-based text-to-3D model where the original text-conditioned diffusion model is replaced with an image-conditioned diffusion model, which we termed SJC-I". Just wondering what does the "image-conditioned diffusion model" refer to? (I guess it's not your finetuned view-conditioned diffusion model, right?)

Thanks!

**Comment by ChrisWu1997** [comment]
It refers to the model in https://huggingface.co/spaces/lambdalabs/stable-diffusion-image-variations, where the original stable diffusion model is tweaked to be conditioned on image input. This is also the model that we used for our fine-tuning. See Appendix C for details.

**Comment by Tsingularity** [comment]
Cool thanks! So for this model, did you control the camera angle with text prompts (just like dreamfusion)?

**Comment by ruoshiliu** [comment]
As an image of an object cannot be assumed to be captured in its canonical lose, it’s unclear how text prompts like dreamfusion can be applied out of the box.
