### ISSUE TITLE
Would it be possible to provide a downloadable link for the rendered images?

### ISSUE THREAD

**Issue by MultiPath** [cvlab-columbia/zero123#19]
Hi, thanks for demonstrating this fantastic work!
I have been following the provided rendering code based on your instructions.
However, as mentioned, the rendering speed is extremely slow, even with 8GPUs.
https://github.com/cvlab-columbia/zero123/issues/4

Do you have an estimation of how long the whole process would take to render the objarvse dataset?
Will it be possible to have a downloadable link, such as Google drive, dropbox, etc for your preprocessed dataset (or even a reasonable size subset)?

Thanks!

**Comment by ruoshiliu** [comment]
Hi @MultiPath , thank you for your interest in our work. We understand the difficulty of rendering the dataset. We are working with huggingface to host our training dataset there for people to download. Stay tuned for the updates the in the next few days!

**Comment by MultiPath** [comment]
Hi, that would be awesome!! Looking forward to running on the same settings soon!

**Comment by claforte** [comment]
Thanks a lot in advance @ruoshiliu for sharing that dataset! Like @MultiPath , I'm also interested in this question:
> Do you have an estimation of how long the whole process would take to render the objarvse dataset?

**Comment by claforte** [comment]
Thanks @ruoshiliu ! Was this using EEVEE or Cycles?

**Comment by claforte** [comment]
> Was this using EEVEE or Cycles?
Nevermind, I see in the paper you used Cycles. Thanks for the great paper and dataset!

**Comment by MultiPath** [comment]
Just wondering any progress on this. Really appreciate it in advance. @ruoshiliu 
I have tested rendering by myself, but I found the speed is much slower than what you showed above.
Will the number of workers affect the rendering speed (I tried 8)? If the data is available soon then I would be super grateful.
Thanks again

**Comment by MultiPath** [comment]
Just to clarify, the problem on my side using CYCLE seems it always showing to be "loading rendering kernel" for each camera view and it is extremely slow.

**Comment by ruoshiliu** [comment]
Still working on the dataset. It could take a few more days. I'll update under this thread when it's ready for download.

The total number of workers was 16 (workers_per_gpu=2) for me and anything beyond that didn't make any difference. Too many workers could put unnecessary load to CPU.

**Comment by ruoshiliu** [comment]
Dataset can be downloaded here:
https://github.com/cvlab-columbia/zero123#objaverse-rendering-preliminary

P.S. This is a temporary solution so the downloading speed can be very slow and can take several days to finish.

**Comment by ruoshiliu** [comment]
Hi all, I'm sorry to let you know that we might need to close downloading of the dataset soon due to higher-than-expected traffic, which is causing some difficulty to our cluster. We are seeking a different solution and will provide updates shortly. It will remain open for the next 24 hours but no guarantee after that. Sorry for the inconvenience.

**Comment by MultiPath** [comment]
My downloading will finish soon in 4 hours. Is it possible to turn off the downloading after tonight? @ruoshiliu

**Comment by MultiPath** [comment]
I can also think about what we can help after downloading this if needed...

**Comment by mitming** [comment]
> Hi all, I'm sorry to let you know that we might need to close downloading of the dataset soon due to higher-than-expected traffic, which is causing some difficulty to our cluster. We are seeking a different solution and will provide updates shortly. It will remain open for the next 24 hours but no guarantee after that. Sorry for the inconvenience.

Hi @ruoshiliu,

May I ask if it can be postponed for a period of time, I still need about 40 hours to download all the data, and I have downloaded 500G so far, it would be a pity for me to just give up. Please remain open for 48 hours, thank you very much!

**Comment by ruoshiliu** [comment]
Quick update: we are setting up a mini-NAS dedicated to hosting the dataset for download. The link will remain active until then. Likely there will also be an option to download from AWS S3.

**Comment by ruoshiliu** [comment]
@mitming , we'll try to keep the link active until we find an alternative way of hosting.

**Comment by mitming** [comment]
> @mitming , we'll try to keep the link active until we find an alternative way of hosting.

Thanks for your effort!

**Comment by ruoshiliu** [comment]
Hi all, the dataset hosted on AWS S3 can be downloaded from here:
```
wget https://tri-ml-public.s3.amazonaws.com/datasets/views_release.tar.gz
```
Please let me know if it works.

**Comment by ruoshiliu** [comment]
Looks like the link has been working as expected -- closing this issue.
