### ISSUE TITLE
Large weight file is hard to download from Google Drive

### ISSUE THREAD

**Issue by LeoXing1996** [cvlab-columbia/zero123#2]
Thanks for this great job 🚀 !
However, the current weight files saved on Google Drive are too large to download. Is there any plan to upload the weight files to huggingface or split them by submodule?

**Comment by ruoshiliu** [comment]
We'll see what we can do and keep you updated!

**Comment by ruoshiliu** [comment]
We are uploading to a huggingface repo. When it's done it'll appear here: https://huggingface.co/datasets/cvlab/zero123-weights

**Comment by ruoshiliu** [comment]
We also temporarily opened downloading with:
```
wget https://cv.cs.columbia.edu/zero123/assets/105000.ckpt
wget https://cv.cs.columbia.edu/zero123/assets/165000.ckpt
```
