### ISSUE TITLE
Unable to train successfully

### ISSUE THREAD

**Issue by greeneggsandyaml** [cvlab-columbia/zero123#20]
Hello and thank you for your very nice paper! 

I am trying to train a view-conditional network using the code in [zero123](https://github.com/cvlab-columbia/zero123/tree/main/zero123), but something is going wrong. I am wondering if my command is wrong, or if there is something else that I am missing. 

I am using the command:
```
python main.py --base configs/sd-objaverse-finetune-c_concat-256.yaml --train --gpus=0,1,2,3 precision=16
```
I have trained for 10,000 steps and it is evident from the generations that something is going wrong. Do you know why this might be / should I be using a different command? 

For context, the logged images look as follows:

`inputs_gs-000000_e-000000_b-000000`:
![inputs_gs-000000_e-000000_b-000000](https://user-images.githubusercontent.com/64370631/228083165-ba159f42-f15b-48f6-9455-9de852d379f6.png)

`conditioning_gs-000000_e-000000_b-000000`:
![conditioning_gs-000000_e-000000_b-000000](https://user-images.githubusercontent.com/64370631/228083162-e34a5d83-bc80-4d8a-af22-1b073ede3f44.png)

`reconstruction_gs-000000_e-000000_b-000000`
![reconstruction_gs-000000_e-000000_b-000000](https://user-images.githubusercontent.com/64370631/228083167-d9881cf5-9efe-4644-b280-351660a7a76a.png)

`samples_gs-000000_e-000000_b-000000`
![samples_gs-000000_e-000000_b-000000](https://user-images.githubusercontent.com/64370631/228083178-7db22723-afa1-4e02-bf8a-16b509893ccc.png)

`samples_cfg_scale_3 00_gs-000000_e-000000_b-000000`
![samples_cfg_scale_3 00_gs-000000_e-000000_b-000000](https://user-images.githubusercontent.com/64370631/228083172-81c73fca-631f-4a21-9fa9-2b2fef5478bc.png)

Thank you so much for your help!

**Comment by ruoshiliu** [comment]
Hi @greeneggsandyaml , we initialized our model weights with the [image-conditioned stable diffusion](https://huggingface.co/lambdalabs/stable-diffusion-image-conditioned) released by lambda-labs. Can you share the loss curve of your training as well? It looks to me like the loss has diverged due to instability. My guess you are using smaller batch size (4 vs 8 gpus), and randomly initialized stable diffusion, causing the training instability. I couldn't find the version of the model weights that I used online for initialization (it's the one from version 2). We are working on releasing the dataset as well so we will release the training script after testing those. In the mean time, feel free to experiment with training randomly initialized SD with different batch size and learning rates.

**Comment by greeneggsandyaml** [comment]
Thanks! I appreciate the quick response.

For training, that makes sense -- no rush. Did you get the image-conditioned SDv2 directly from Lambda Labs then, rather thank finding it online?

**Comment by ojmichel** [comment]
Hi thank you very much for sharing this amazing work. I was able to find these checkpoints from Lambda Labs [https://huggingface.co/lambdalabs/stable-diffusion-image-conditioned/tree/main](url). Are either of these correct? The code was able to load sd-clip-vit-l14-img-embed_full.ckpt when I tried. 

Also, would it be possible to release some training documentation? Even if the dataset and checkpoints are not yet able to be released, it would be helpful to have some guidance on running training.

**Comment by ojmichel** [comment]
Hi thank you very much for sharing this amazing work. I was able to find these checkpoints from Lambda Labs [https://huggingface.co/lambdalabs/stable-diffusion-image-conditioned/tree/main](url). Are either of these correct? The code was able to load sd-clip-vit-l14-img-embed_full.ckpt when I tried. 

Also, would it be possible to release some training documentation? Even if the dataset and checkpoints are not yet able to be released, it would be helpful to have some guidance on running training.

**Comment by ruoshiliu** [comment]
Hi all, sorry for the delay. I've updated the readme file for the training script. Could you please try the commands [here](https://github.com/cvlab-columbia/zero123/blob/main/README.md#training-script-preliminary) and let me know if it works?

**Comment by greeneggsandyaml** [comment]
Thanks! I will try it out and let you know how it works.

**Comment by CiaoHe** [comment]
@ruoshiliu I tried the updated training script [training-script](https://github.com/cvlab-columbia/zero123/blob/main/README.md#training-script-preliminary), but found the CLIPImageEncoder doesn't match with the config file `sd-objaverse-finetune-c_concat-256.yaml`:

sd-objaverse-finetune-c_concat-256.yaml writes
```yaml
cond_stage_model.model.visual.xxxxx
```

but lambdalabs ckpt gives 
```yaml
cond_stage_model.transformer.vision_model.xxxxx
```
perhaps the lambdalabs ckpt listed in README doesn't matching with your original training network architecture config

**Comment by ruoshiliu** [comment]
@CiaoHe Did you manage to train it successfully?

**Comment by CiaoHe** [comment]
yeah i can train now

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ruoshi Liu ***@***.***>
发送时间: Wednesday, April 12, 2023 3:06:09 AM
收件人: cvlab-columbia/zero123 ***@***.***>
抄送: He Cao ***@***.***>; Mention ***@***.***>
主题: Re: [cvlab-columbia/zero123] Unable to train successfully (Issue #20)


@CiaoHe<https://github.com/CiaoHe> Did you manage to train it successfully?

―

**Comment by yuanzhi-zhu** [comment]
Hi @CiaoHe,

Do you still get 
> missing keys:
> ['cc_projection.weight', 'cc_projection.bias']

after using the new img-cond-sd checkpoint (and a bunch of unexpected keys)

**Comment by CiaoHe** [comment]
> Hi @CiaoHe,
> 
> Do you still get
> 
> > missing keys:
> > ['cc_projection.weight', 'cc_projection.bias']
> 
> after using the new img-cond-sd checkpoint (and a bunch of unexpected keys)
> 
> I am also curious how did you make it work with precision=16 as I always got errors like
> 
> > RuntimeError: expected scalar type Half but found Float.

I think 
 > missing keys:
> ['cc_projection.weight', 'cc_projection.bias']
is normal, since the original sd-ckpt doesn't have the `cc_projection` layer which is initialized and trained in zero123

**Comment by ruoshiliu** [comment]
Hi all, I tested both the pretrained checkpoint provided in our [repo](https://github.com/cvlab-columbia/zero123#training-script-preliminary) and the one provided on lambda labs huggingface linked by @CiaoHe [here](https://huggingface.co/lambdalabs/stable-diffusion-image-conditioned/blob/main/sd-clip-vit-l14-img-embed_full.ckpt). Both should work. The former is the second version of the latter which is trained for more iterations, but shouldn't affect zero123 training too much.

**Comment by yhyang-myron** [comment]
> @ruoshiliu I tried the updated training script [training-script](https://github.com/cvlab-columbia/zero123/blob/main/README.md#training-script-preliminary), but found the CLIPImageEncoder doesn't match with the config file `sd-objaverse-finetune-c_concat-256.yaml`:
> 
> sd-objaverse-finetune-c_concat-256.yaml writes
> 
> ```yaml
> cond_stage_model.model.visual.xxxxx
> ```
> 
> but lambdalabs ckpt gives
> 
> ```yaml
> cond_stage_model.transformer.vision_model.xxxxx
> ```
> 
> perhaps the lambdalabs ckpt listed in README doesn't matching with your original training network architecture config
> 
> ps, I found lambdalabs gitrepo https://github.com/justinpinkney/stable-diffusion, just for anyone interest And the right img-cond-sd ckpt should be [here](https://huggingface.co/lambdalabs/stable-diffusion-image-conditioned/blob/main/sd-clip-vit-l14-img-embed_full.ckpt), rather below described in README @greeneggsandyaml
> 
> > Download image-conditioned stable diffusion checkpoint released by [Lambda Labs](https://huggingface.co/spaces/lambdalabs/stable-diffusion-image-variations)

@ruoshiliu Hi, thank you for your great work! I still met this problem when using the checkpoint provided in the repo.

**Comment by jh27kim** [comment]
> > @ruoshiliu I tried the updated training script [training-script](https://github.com/cvlab-columbia/zero123/blob/main/README.md#training-script-preliminary), but found the CLIPImageEncoder doesn't match with the config file `sd-objaverse-finetune-c_concat-256.yaml`:
> > sd-objaverse-finetune-c_concat-256.yaml writes
> > ```yaml
> > cond_stage_model.model.visual.xxxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but lambdalabs ckpt gives
> > ```yaml
> > cond_stage_model.transformer.vision_model.xxxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > perhaps the lambdalabs ckpt listed in README doesn't matching with your original training network architecture config
> > ps, I found lambdalabs gitrepo https://github.com/justinpinkney/stable-diffusion, just for anyone interest And the right img-cond-sd ckpt should be [here](https://huggingface.co/lambdalabs/stable-diffusion-image-conditioned/blob/main/sd-clip-vit-l14-img-embed_full.ckpt), rather below described in README @greeneggsandyaml
> > > Download image-conditioned stable diffusion checkpoint released by [Lambda Labs](https://huggingface.co/spaces/lambdalabs/stable-diffusion-image-variations)
> 
> @ruoshiliu Hi, thank you for your great work! I still met this problem when using the checkpoint provided in the repo.

@ruoshiliu Hi, I also encountered the same problem. 
Could you please verify which checkpoint we should finetune from ? 

Thanks
