### ISSUE TITLE
Killed : cd zero123/zero123, then python gradio_new.py, get Killed

### ISSUE THREAD

**Issue by wlupc** [cvlab-columbia/zero123#21]
cd zero123/zero123, then python gradio_new.py, the program gets Killed.
The code locates in ' zero123/zero123/ldm/models/diffusion/ddpm.py ', 
********************************************************************************
    def instantiate_cond_stage(self, config):
        if not self.cond_stage_trainable:
            if config == "__is_first_stage__":
                print("Using first stage also as cond stage.")
                self.cond_stage_model = self.first_stage_model
            elif config == "__is_unconditional__":
                print(f"Training {self.__class__.__name__} as an unconditional model.")
                self.cond_stage_model = None
                # self.be_unconditional = True
            else:
                model = instantiate_from_config(config)
*********************************************************************************
**instantiate_from_config** gets error,  **config** is ' cond_stage_config:target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder'.
Did anyone else encounter similar situations？

**Comment by ruoshiliu** [comment]
Could be an issue related to installing environments for CLIP. Try running:
```
git clone https://github.com/openai/CLIP.git
pip install -e CLIP/
```
