### ISSUE TITLE
How to get the image data when training ?

### ISSUE THREAD

**Issue by liuxz-cs** [cvlab-columbia/zero123#24]
Hello, I want to know how to get the image data for training, I only download the objaverse data from huggingface with the '.glb' file, and when I run the training scripts, It seems it try to load the image from`.objaverse/hf-objaverse-v1/692db5f2d3a04bb286cb977a7dba903e_1/002.png`, but I do not have these image data with '.png'.

By the way, in line 282 in `zero123/zero123/ldm/data/simple.py`, the `sys` is not defined in this file.

**Comment by ruoshiliu** [comment]
Hi @liuxz-cs , thank you for pointing out the bug -- just fixed. Given the objaverse dataset you can either render the dataset yourself using the blender script we provided [here](https://github.com/cvlab-columbia/zero123/tree/main/objaverse-rendering), or download the renderings we used [here](https://github.com/cvlab-columbia/zero123#objaverse-rendering-preliminary).
