### ISSUE TITLE
How to test the ckpt?

### ISSUE THREAD

**Issue by wzic** [cvlab-columbia/zero123#26]
Hi!
I have seen the updated README about training. Will you also release the command for testing? 
Also, may I know how to use the ObjaverseDataModuleFromConfig by myself to have a flexible control, instead of using the trainer.fit()?

**Comment by ruoshiliu** [comment]
We didn't test on objaverse as the paper focuses on zero-shot generalization. If you want testing scripts on a custom dataset, the demo app will be a good starting point. It provides a testing function -- the model takes in an image and rotates it to specified angles. Closing the ticket for now.
