### ISSUE TITLE
Data Download is too slow.

### ISSUE THREAD

**Issue by LeeDoYup** [cvlab-columbia/zero123#27]
Hello! Thanks for the awesome project and releasing the models and data !
By the way, I found that downloading rendered images is too slow (about 30KB/s). 

Is there any other way to download the dataset?
Thanks !

**Comment by ruoshiliu** [comment]
It's to be expected. We are seeking alternative ways to host the dataset. Stay tuned!

**Comment by ruoshiliu** [comment]
Hi @LeeDoYup , please see #19

**Comment by LeeDoYup** [comment]
Thank you for releasing the link !!!
