### ISSUE TITLE
where is this config ? 

### ISSUE THREAD

**Issue by pengwangucla** [cvlab-columbia/zero123#3]
Nice work !

`configs/sd-objaverse-finetune-c_concat-256.yaml`

it can not find the config and corresponding last.ckpt model. 

Will it be shared later

**Comment by ruoshiliu** [comment]
Could you please share the command you are running and the error message? We have shared the model weights here: https://drive.google.com/drive/folders/1geG1IO15nWffJXsmQ_6VLih7ryNivzVs
