### ISSUE TITLE
Question about Objaverse rendering

### ISSUE THREAD

**Issue by pigtigger** [cvlab-columbia/zero123#31]
Hi, authors of zero123,

I wonder if it is necessary to filter out some objects in Objaverse when creating the dataset since some instances are too weird (e.g. a single paper). And have you filtered the dataset you provide in this repo? Could you give me some suggestions?

**Comment by ruoshiliu** [comment]
I understand your concern as the quality of the instances vary quite a lot in Objaverse but overall I didn't find this to be very problematic for training. Now that our renderings are available for download, there could be some image based filtering to be done pretty easily. Whether or not it helps would depend on the tasks.
