### ISSUE TITLE
Some error of the dataloader.

### ISSUE THREAD

**Issue by liuxz-cs** [cvlab-columbia/zero123#33]
Thanks a lot for releasing this training scripts and data. When I run the training scrips, I get some errors. 

We originally extract 100 objects from the dataset, and we run in 2 GPUs with the 32GB of VRAM, we set `batch_size=16, num_workers=8` in `config/sd-objaverse-finetune-c_concat-256.yaml`, and it can run successfully. 

However, then we use a larger dataset of 2000 objects, and continue to keep `batch_size=16, num_workers=8`, then get the error `RuntimeError: DataLoader worker (pid(s) 8298) exited unexpectedly`. I modify the `config/sd-objaverse-finetune-c_concat-256.yaml`. We try to set `batch_size` or `num_workers` to be smaller, but it still get the same error. We also try to set `num_workers=0` and it did not work. Only we set `batch_size=1`，it did not have this error. So, I want to know where the error may occur, and is there any solution to solve this problem?

**Comment by cwchenwang** [comment]
how did you solve this problem?

**Comment by ys830** [comment]
I met the same error, how did you solve this problem?

**Comment by liuxz-cs** [comment]
> I met the same error, how did you solve this problem?

Actually，I find there exists error in the data itself.  There exists the data sample to be invalid or null, so maybe you need to check your downloaded dataset.
