### ISSUE TITLE
Could you please provide the code for multi-node rendering?

### ISSUE THREAD

**Issue by mitming** [cvlab-columbia/zero123#34]
Hi @ruoshiliu,

Thanks for your contribution, I'm trying to quickly test an idea, but I need to re-render the data set. I noticed that your previous answer mentioned using 10 machines to render, can you provide code and tutorials for multi-machine rendering?

**Comment by ruoshiliu** [comment]
If you run the command across 10 machines, they will check for conflicts with:

https://github.com/cvlab-columbia/zero123/blob/b37ba66f015c7bd971c070318dd59da350265fe0/objaverse-rendering/scripts/distributed.py#L47

It's a very ad-hoc solution but it works.

**Comment by mitming** [comment]
> 

Cool~ Thanks for your help, I can just run the same code on other machines.
