### ISSUE TITLE
Questions on dataloader

### ISSUE THREAD

**Issue by cwchenwang** [cvlab-columbia/zero123#35]
Hi, I appreciate your excellent work. I tried to download your data and ran your train script. However, the released data has no file 'valid_paths.json' (I managed to find it in another issue), is it just all the subfolder names in views_release folder? Also in your dataset code:
```
if self.paths[index][-2:] == '_1': # dirty fix for rendering dataset twice
            total_view = 8
        else:
            total_view = 4
```
which means total view for each subfolder is 8 or 4. However, I found in my downloaded data, most scenes have more than 10 views, do you only random from 4 or 8 views during training?

**Comment by ikuinen** [comment]
I am also curious about that.
