### ISSUE TITLE
Mesh extraction in 3D reconstruction

### ISSUE THREAD

**Issue by j0seo** [cvlab-columbia/zero123#36]
Hi, @ruoshiliu  Thank you for making your incredible work public! 
I'm looking into the code for 3D reconstruction based on SJC, and wondering if there is a code for extracting the mesh from the generated 3D, like what has been shared on the project page. Or, if there are any libraries or code repositories used, that information would also be of great help. Thank you!

**Comment by ChrisWu1997** [comment]
We have the `export_mesh` function [here](https://github.com/cvlab-columbia/zero123/blob/d948dd9e92a276fca8358cc7a93c681a5947973d/3drec/voxnerf/vox.py#L71) for extracting the mesh from the voxel nerf. Tune the input arguments if the exported mesh looks bad.

**Comment by j0seo** [comment]
Thanks for your kind response!

**Comment by dov84d** [comment]
Hi @j0seo, thank you for the incredible work.
Do you have a code for exporting the mesh with a texture?
