### ISSUE TITLE
Regarding the released objaverse renderings

### ISSUE THREAD

**Issue by MukundVarmaT** [cvlab-columbia/zero123#37]
Hi, Thank you for amazing work!

I was able to download the renderings provided in the repository. However, I was not able to find the camera intrinsic (e.g focal length or camera angle) nor the near and far depths of each scene. I wanted to check if I was missing something?

Also I wanted to confirm, the downloadable renderings do not contain the depth maps from each view right?

Thanks

**Comment by ruoshiliu** [comment]
Hi @MukundVarmaT , thank you for your interest in our work. 
For intrinsics:
> We assume the horizontal field of view of the camera to be 49.1◦, and follow a pinhole camera model

Depth maps are not included as model is not trained on depth maps.

**Comment by MukundVarmaT** [comment]
Hi @ruoshiliu 

Thank you for the prompt response. I also wanted to confirm the near and far depth of the scene.

**Comment by ruoshiliu** [comment]
I think you might be misunderstanding NeRF and blender renderings. Near and far depth are hyperparameters for NeRF determining the size of the neural fields. Our renderings are rendered in blender where a 3D asset is first loaded, preprocessed, a camera is initialized and placed at a randomly sampled location. All of these detailed information in terms of specific rendering settings can be found in the appendix section of the paper.

**Comment by thucz** [comment]
Hi! Sorry to disturb you. If I want to get the depthmaps for each view based on your rendering script, do you have any idea to make it? @ruoshiliu

**Comment by smileyenot983** [comment]
> Hi! Sorry to bother you. If I want to get the depthmaps for each view based on your rendering script, do you have any idea to make it? [@ruoshiliu](https://github.com/ruoshiliu)
you can run some monocular depth estimation method, like depthanything
