### ISSUE TITLE
How many objaverse objects are used when finetuning

### ISSUE THREAD

**Issue by CiaoHe** [cvlab-columbia/zero123#4]
hi, first show great respect to this work!
I just wondering how many `objaverse` objects are used in this project? I see the `objaverse` dataset is quite large lol. 
Perhaps you can provide some tutorial about processing `objaverse` dataset?(like rendering etc)

Best,

**Comment by ruoshiliu** [comment]
Hi, thank you for the kind words! We have released our rendering script here: https://github.com/cvlab-columbia/zero123/blob/main/objaverse-rendering/scripts/render.sh

Also checkout the original objaverse-rendering repo: https://github.com/allenai/objaverse-rendering
And the downloading instruction of objaverse: https://objaverse.allenai.org/docs/download

Hope this helps!

**Comment by CiaoHe** [comment]
nice to hear the feedback.
Emmm, so this project do really using the whole `objaverse` dataset (800k objects * 12views/each -> ~10M images as mentioned in the paper). Wow, I remember the whole dataset is ~8.5T, my disk...

**Comment by CiaoHe** [comment]
Yeah I agree, ft the foundation model is a tech. Have'u tried use smaller dataset (to check the performance degradation)?

**Comment by jfozard** [comment]
The renderings would be a wonderful resource - maybe HF will host them?

**Comment by ruoshiliu** [comment]
We haven't tried finetuning on smaller dataset than Objaverse but it'll be interesting experiments to try! Currently no plan to host renderings as Objaverse is actively increasing in size. Our copy will most likely be outdated in a few months anyways.
