### ISSUE TITLE
Source of testing images in the paper

### ISSUE THREAD

**Issue by XinyangHan** [cvlab-columbia/zero123#45]
Dear friends! I really appreciate your work and your caution of choosing testing images out of objavserse distribution! May I ask your way of choosing testing objects? (To be more concrete, do you have any advice on choosing 3D object testing dataset so that we can test it with ground truth?)

**Comment by ruoshiliu** [comment]
Hi @XinyangHan , I took a bunch of pictures of objects in our lab and my apartment as those objects are most likely not in the objaverse dataset. In addition, we find images on the internet as well. But these are mostly for qualitative experiments. For a 3D testing dataset with 3D ground truth, the available datasets are probably much more limited. To name a few that are on top of my mind, there are GSO, CO3D, RTMV, ShapeNet. In terms of choosing which objects to use within the dataset, we just randomly sample a subset and run experiments on those. We didn't cherry-pick within a dataset.

**Comment by XinyangHan** [comment]
Got it!!! Thanks so much for replying!! Btw, when testing on in-the-wild images, it seems that the segmentation would have a little artifacts like shown below. Just wondering if you have some advice on matting in the wild images as input or plan to improve the processing module~
Thanks again for your kindly help~
![image](https://user-images.githubusercontent.com/86959032/233911336-b9e0fb4a-e92e-415d-acb8-e7660dd47a97.png)
![image](https://user-images.githubusercontent.com/86959032/233911779-d61cf922-6664-49ae-98a3-15f0f53f8a2c.png)

**Comment by XinyangHan** [comment]
Thanks so much for your help!!!
