### ISSUE TITLE
Lack of evaluation code and confusion on evaluation dataset

### ISSUE THREAD

**Issue by xyyeah** [cvlab-columbia/zero123#46]
Thanks for the interesting work and for releasing the code. Could you please provide more details on the evalution steps in your experiments ? Additionaly, I noticed that you evaluated the method on the GSO dataset and RTMV dataset, but it seems that the GSO dataset is a subset of  [RTMV dataset](http://www.cs.umd.edu/~mmeshry/projects/rtmv/). Could you please clarify the evaluation procees and provide more information on how you evaluated on these two dataset ?

**Comment by ruoshiliu** [comment]
Hi @xyyeah , thank you for your interest in our work. I wouldn't say GSO is a subset of RTMV. A subset of RTMV, named Google Scanned Object, is composed of 300 scenes, each with 20 GSO objects. Therefore, each scene's geometry and texture is much more complicated than any single object in GSO. The experiments section of the paper as well as the appendix section have covered a lot of details regarding the evaluation process. Feel free to let me know if there's still anything unclear.

**Comment by xyyeah** [comment]
Thank you for your quick reply, I figured out the difference between GSO dataset and subset in RTMV. But I found that there are 2.5T data in the RTMV dataset, did you evaluate all the datasets or only a subset? If it is a subset, which subset did you evaluate?

**Comment by ruoshiliu** [comment]
We used 20 scenes randomly sampled from the Google Scanned Obejct subset, each scene with 17 novel views (1 for input and 16 for evaluation). Zero123 is very fast at inference time so we can easily evaluate hundreds of scenes. The difficulty in including more scenes for evaluation is that it's very expensive to train DietNeRF (one of our baseline). It takes around 24 hours to train one scene for DietNeRF on 1 GPU.

**Comment by taeyeopl** [comment]
@ruoshiliu Thanks for your explanation. 

If I want to reproduce the same results of yours in Table 1 and Table 2 as you did, Can you give some information on which 20 scenes and 17 novel views are used and 1 for the input? If datasets are not large, sharing both GSO and RTMV information will be really helpful.

**Comment by xyyeah** [comment]
@ruoshiliu Thanks for your quick reply.

I would like to reproduce the same evaluation results showed in the paper. I have downloaded the GSO dataset but cannot find any paired image/camera poses. Could you share more information about the preprocess method used to obtain the test datasets for the results in Table 1 and Table 2? Or as @taeyeopl suggested, could you share the preprocessed GSO and RTMV datasets ?

**Comment by XinyangHan** [comment]
@ruoshiliu Looking for code for GSO and RTMV as well~ It would be great if these preprocessing codes are released!!

**Comment by ruoshiliu** [comment]
Here's the script to render 25 views for GSO: [gso_render.zip](https://github.com/cvlab-columbia/zero123/files/11377545/gso_render.zip). I believe the RTMV dataset already contains 150 rendered views for each scene.

**Comment by XinyangHan** [comment]
Thanks so much for your help!!!

**Comment by jwlee-vcl** [comment]
@ruoshiliu Thanks for your rendering scripts.

It looks like the model names are in the test.json in your script, if you could share the test.json I would appreciate it.
