### ISSUE TITLE
Detailed parameters of cameras when generating renders results from Objaverse

### ISSUE THREAD

**Issue by ZexinHe** [cvlab-columbia/zero123#48]
Hi, thanks for providing the 1.5T rendered views!

As I'm using this dataset for my research, it occurs that only the transformation matrices are provided, while other camera parameters are missing, such as `fov`, `camera_angle_x`, `rotation`, etc (those from BlenderDataset). Since we are using the objects from Objaverse, where GTs are provided, it would be better to skip the calibration step and use the information from the 3D asset. Therefore, I'm wondering if you could provide more data about how each object is rendered.

Thanks!

**Comment by ruoshiliu** [comment]
Hi @ZexinHe , fov is the same thing as camera_angle_x in NeRF's blender dataset, which is 49.1 degree or 0.857 rad as stated in the appendix section of the paper. I might be wrong but I think rotation is not part of the camera intrinsics for NeRF. It describes the rotation angle between two consecutive viewpoints.

**Comment by ZexinHe** [comment]
Thanks for your timely feedback! I've found the details now. And you are right about rotation, the information is contained in the sequence of transformation matrices.

**Comment by yjcaimeow** [comment]
Hi @ZexinHe ,  So，I want to make sure whether right using the following equations to obtain the intrinsic K for objaverse dataset ?

```
H, W = imgs[0].shape[:2]
camera_angle_x = float(meta['camera_angle_x'])
f = 1 / np.tan(camera_angle_x / 2) * (W / 2)
```

Best,
Ying

**Comment by ZexinHe** [comment]
Hi @yjcaimeow , 

I think you are correct. The above code obtains the focus, which leads to the intrinsic K matrix.
K=[[f,0,W/2], [0,f,H/2], [0,0,1]]

Bests,
Zexin
