### ISSUE TITLE
will the training codes also be released?

### ISSUE THREAD

**Issue by LeeDoYup** [cvlab-columbia/zero123#5]
Thanks for the awesome project !
I wonder whether the training codes of this study are also released or not !

Again, thanks for the awesome and very cool project.

**Comment by ruoshiliu** [comment]
We have released the training config file: https://github.com/cvlab-columbia/zero123/blob/main/zero123/configs/sd-objaverse-finetune-c_concat-256.yaml
The training script is `main.py`

**Comment by LeeDoYup** [comment]
@ruoshiliu Thanks for the reply !
