### ISSUE TITLE
R matrix from gradio_new.py

### ISSUE THREAD

**Issue by cwwjyh** [cvlab-columbia/zero123#52]
I have checked Appendix Section A of the paper regarding the camera coordinate system. In gradio_new.py, Is the Rotation matrix(camera_R ) in w2c format?
In gradio_new.py, you use **camera_R** to obtain the camera extrinsic but not given  T matric of the camera. So I want to use pytorch3d [look_at_view_transform](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/cameras.html#look_at_view_transform) to compute
 extrinsic matric R|t using: **R, T = look_at_view_transform(dist=radius, elev=90 - polar_deg, azim=azimuth_deg, up=((0, 1, 0),))**. but I got a different result. In the image below, the result of R_jisuan is used pytorch3d to compute, and the camera_R_ori is your code result. how to compute the same R using pytorch3d in your code. Or you can give me advice on how to use your code to compute the T matric of the camera.
![f60ef7890fbf88315aa0a7a45ff71a6](https://user-images.githubusercontent.com/26154160/236131983-e4d2eba2-ee56-42d8-b72e-27ad230b92b5.png)
Looking forward to your reply!

**Comment by cwwjyh** [comment]
> The matrices calculation in gradio_new.py is only for angle visualization purposes and is independent of the zero123 inference code, so I wouldn't use one to understand another.
> 
> Assuming you are asking zero123 inference conditioning, here's the [code](https://github.com/cvlab-columbia/zero123/blob/f70ea8c26af7943494f75314df054eb843999add/zero123/ldm/data/simple.py#L257-L272) converting a pair of camera matices (input view and target view) into the 4-dimensional conditioning vector described in appendix section A.
> 
> Hope it makes sense.
> 
> P.S. camera matrices over parameterized the transformation so there'll be more than one way to represent an RT operation. I think a better way to compare RT is to visualize the camera or to convert it to Euler or axis angle first.

if I use  **camera_R** to calculate the rotation matric in gradio_new.py, is the **camera_R** the target image's rotation matric or not?

**Comment by ruoshiliu** [comment]
Sorry but I don't understand. What do you need camera_R, which is used for visualization, for?

**Comment by ruoshiliu** [comment]
If you want to generate a novel view based on a sampled target viewpoint described by an RT matrix, assuming your input viewpoint is cond_RT, you can sample a target viewpoint target_RT, and use the get_T function to get d_T which is the conditioning information for zero123: https://github.com/cvlab-columbia/zero123/blob/f70ea8c26af7943494f75314df054eb843999add/zero123/ldm/data/simple.py#L257-L272

**Comment by cwwjyh** [comment]
> If you want to generate a novel view based on a sampled target viewpoint described by an RT matrix, assuming your input viewpoint is cond_RT, you can sample a target viewpoint target_RT, and use the get_T function to get d_T which is the conditioning information for zero123:
> 
> https://github.com/cvlab-columbia/zero123/blob/f70ea8c26af7943494f75314df054eb843999add/zero123/ldm/data/simple.py#L257-L272

Thank you! I will try it. Can I write the above code in gradio_new.py to get the target Rt matric?

**Comment by ruoshiliu** [comment]
This function does (cond_RT, target_RT) -> d_T. Sounds like you want (cond_RT, d_T) -> target_RT. You will need to implement that yourself.

**Comment by cwwjyh** [comment]
> This function does (cond_RT, target_RT) -> d_T. Sounds like you want (cond_RT, d_T) -> target_RT. You will need to implement that yourself.

cond_RT means input image RT, target_RT means synthesize view RT, what's mean d_T?
![1683256486555](https://user-images.githubusercontent.com/26154160/236370802-c6e0fc23-e01e-4b85-a90b-b71886a4eb2c.jpg)

**Comment by ruoshiliu** [comment]
It means the relative transformation from cond_RT to target_RT, which is used as input to the diffusion model: https://github.com/cvlab-columbia/zero123/blob/f70ea8c26af7943494f75314df054eb843999add/zero123/gradio_new.py#L81-L82

I suggest you try to understand the paper/code before raising an issue here. Closing the ticket for now.
