### ISSUE TITLE
Training File Corrupted?

### ISSUE THREAD

**Issue by wangmiaowei** [cvlab-columbia/zero123#56]
Thanks for your provision about this training dataset. But when I unzip this tar.gz, I get a corruption error during unzipping. I check downloaded file size is about 1615599040379 bytes. 
1615599040379 Apr  7 23:42 views_release.tar.gz

Could you help me figure out?

**Comment by ruoshiliu** [comment]
Hi @wangmiaowei , I'm sorry but I don't know what's going on with this issue. I had used the link to download from various environments and systems and never had issue. Closing this ticket for now.
