### ISSUE TITLE
Is live-demo closed now?

### ISSUE THREAD

**Issue by Dystopians** [cvlab-columbia/zero123#58]
Sorry to bother
Found the live-demo https://huggingface.co/spaces/cvlab/zero123-live stuck in building process for several days. Used to successfully built but that was 3 days ago>>
Anything wrong with the live-demo?

**Comment by ruoshiliu** [comment]
It's back online now! Not sure what was wrong with it in the past few days either ...

**Comment by fire** [comment]
Upgrade `gradio>=3.36.1`

**Comment by ruoshiliu** [comment]
Apology for the downtime, the demo should be up and functional again... There was indeed a package incompatibility issue due to upgrade of pydantic.
