### ISSUE TITLE
zero123 XL

### ISSUE THREAD

**Issue by XinyangHan** [cvlab-columbia/zero123#59]
Congratulations for the released of zero123 XL!!! Is it trained using exact the same model as zero123, and just differs in data?

**Comment by jclarkk** [comment]
It seems something is weird here since both the zero123-xl.ckpt and the 10500.ckpt are the exact same file size.

**Comment by tydia** [comment]
they did not change the model structure, just finetuned on more data with objaverse-xl as suggested in objaverse-xl's preprint

FYI: https://objaverse.allenai.org/objaverse-xl-paper.pdf

**Comment by ruoshiliu** [comment]
@tydia correct, zero123-xl is designed as a drop-in replacement for zero123. Previously zero123 showed some signs of overfitting when trained on objaverse for an extended period of time, so with zero123-xl we decided not to scale the model while scaling the dataset.

**Comment by HeliosZhao** [comment]
May I ask where the `zero123-xl.ckpt` is? In the [hugging face model](https://huggingface.co/cvlab/zero123-weights), I can only find `105000.ckpt` and `165000.ckpt`.
