### ISSUE TITLE
Optimise vram requirements to 16GB

### ISSUE THREAD

**Issue by vadi2** [cvlab-columbia/zero123#6]
Thanks for this fantastic work!

I appreciate the effort it took to fit the model in 22GB. Would it be possible to squeeze it further down to 16GB? I'd love to be able to run it on my card (rtx 4080).

**Comment by ruoshiliu** [comment]
There should be a few things that can be taken off of the GPU (e.g. the background remover and NSFW checker). Right now it's taking around 17.3GB on my GPU which is almost there. We'll look into this at some point. In the mean time, if you figure out a way to reduce the VRAM without loosing inference quality, feel free to submit a pull request.

Btw, check out our live demo on huggingface if you haven't yet: https://huggingface.co/spaces/cvlab/zero123-live

**Comment by ruoshiliu** [comment]
Also, you can choose 1 sample instead of 4 to reduce the VRAM,

**Comment by iivek** [comment]
@vadi2 you might be interested to take a look at [one version of the demo](https://github.com/iivek/zero123-accelerate) that uses < 15GB of VRAM
