### ISSUE TITLE
extracting objaverse renderings failed

### ISSUE THREAD

**Issue by kamzero** [cvlab-columbia/zero123#66]
Hello,

I followed this issue [https://github.com/cvlab-columbia/zero123/issues/19 ↗](https://github.com/cvlab-columbia/zero123/issues/19) to download the Objaverse Renderings dataset using the following command:

`wget https://tri-ml-public.s3.amazonaws.com/datasets/views_release.tar.gz`

The download process completed successfully, but after several attempts to extract the files, I only managed to extract around 20,000 rendered images of objects. I suspect there might be an issue with the file itself.

Could you please help me confirm if there is any issue with this file?

Thank you.

**Comment by ruoshiliu** [comment]
Hi @kamzero , I've downloaded the views and extracted them multiple times with different environment and systems without problem so I don't think the file itself has any issue.

**Comment by kamzero** [comment]
Thank you for your reply.  I will revisit my download process to ensure that everything is done correctly.
