### ISSUE TITLE
EMA weights for inference?

### ISSUE THREAD

**Issue by Trainingzy** [cvlab-columbia/zero123#68]
Hi, thanks for your great work. 

I am not familiar with this codebase, and I am asking if you use the ema weights or the trainable weights for inference. There exist ema weights in your `.ckpt` file, but from the inference process, i.e., `apply_model` method, I do not see the use of ema model. So  what is the ema weight used for?

**Comment by ruoshiliu** [comment]
Hi @Trainingzy , it's indeed not used -- just legacy code.

**Comment by Trainingzy** [comment]
Thanks for the reply~
