### ISSUE TITLE
How to retrain zero123?

### ISSUE THREAD

**Issue by VLadImirluren** [cvlab-columbia/zero123#73]
Thanks for your greate implementation and excellent paper !!
I want to retrain zero 123, but I don't know how to make the valid_paths.json.
Can you tell me how you make it? I will be grateful if you can give me some advice.
Thanks again!

**Comment by VLadImirluren** [comment]
Most important is that I want to remake the pair of {(x, x(R,T ), R, T )}, how can I do？
I want to change the x(R, T).Please give me some advice....

**Comment by VLadImirluren** [comment]
“For each object in the dataset, we randomly sample 12 camera extrinsics matrices Me pointing at the center of the object and render 12 views with a raytracing engine”.
I found the decription above in paper,.Can you share the script about making the dataset with me....I really need it....

**Comment by VLadImirluren** [comment]
Another question is how to match the png,npy to the .glb file ?
I just took a look at the dataset, but I found that the folder name isn't same as the .glb in abjaverse....
THANKS.....

**Comment by ChengWan9** [comment]
Have you solved?I also want to retrain zero123,but I dont know how to do.Can you help me?
