### ISSUE TITLE
hugging face live demo down

### ISSUE THREAD

**Issue by ar4s-eth** [cvlab-columbia/zero123#95]
You're demo on HF seems to be having technical difficulties ;)

https://huggingface.co/spaces/cvlab/zero123-live

**Comment by ruoshiliu** [comment]
It's now back up!

**Comment by Tauseefahmed1451** [comment]
![image](https://github.com/cvlab-columbia/zero123/assets/145332470/c1885ce9-5161-43c7-a183-7d42a430a2db)
The demo is still down
