### ISSUE TITLE
inference with 300000.ckpt

### ISSUE THREAD

**Issue by ChengWan9** [cvlab-columbia/zero123#99]
Dear authors,
Thank you for the great work.
When I inference my sofa picture with 300000.ckpt，parts of the generated image that were previously invisible are always black.Is it normal?How can I imporove this situation?
Besides,when I inference my sofa picture with 300000.ckpt，Generated images are no longer random(The results generated several times are almost the same)，why does it happen？
![image](https://github.com/cvlab-columbia/zero123/assets/143673887/434a274a-9b1a-4b09-abea-06005624c39b)

**Comment by ruoshiliu** [comment]
Hi @gitsawww, it is normal. Feel free to try out [zero123-xl](https://zero123.cs.columbia.edu/assets/zero123-xl.ckpt), which should have this problem fixed. It happens due to how the training dataset (objaverse) is rendered. We used a single point light source with randomized location.

**Comment by ChengWan9** [comment]
> Hi @gitsawww, it is normal. Feel free to try out [zero123-xl](https://zero123.cs.columbia.edu/assets/zero123-xl.ckpt), which should have this problem fixed. It happens due to how the training dataset (objaverse) is rendered. We used a single point light source with randomized location.

thanks for your apply!
I also tried zero123-xl before,but it seemes that it doesn't work better than 300000.ckpt?

**Comment by ChengWan9** [comment]
> > Hi @gitsawww, it is normal. Feel free to try out [zero123-xl](https://zero123.cs.columbia.edu/assets/zero123-xl.ckpt), which should have this problem fixed. It happens due to how the training dataset (objaverse) is rendered. We used a single point light source with randomized location.
> 
> thanks for your apply! I also tried zero123-xl before,but it seemes that it doesn't work better than 300000.ckpt?

maybe just in my case
